name = "cf-proxy" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[route]]
pattern = "vpn.salut.biz.id"
custom_domain = true
[[route]]
pattern = "quiz.int.vidio.com.vpn.salut.biz.id"
custom_domain = true
[[route]]
pattern = "quiz.staging.vidio.com.vpn.salut.biz.id"
custom_domain = true
[[route]]
pattern = "quiz.vidio.com.vpn.salut.biz.id"
custom_domain = true
[[route]]
pattern = "support.vidio.com.vpn.salut.biz.id"
custom_domain = true
[[route]]
pattern = "img.email1.vidio.com.vpn.salut.biz.id"
custom_domain = true

[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
PROXY_BANK_URL = "https://raw.githubusercontent.com/FoolVPN-ID/Nautica/refs/heads/main/proxyList.txt"
REVERSE_PROXY_TARGET = "https://vpn.salut.biz.id"
UUID = "c1966e85-7753-4153-adc3-2d8c04c3bb7b"

[unsafe.metadata.observability]
enabled = true

[observability.logs]
enabled = true
